import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class WorkHourDAO {
    // Create database connection object
    DatabaseConnection db = new DatabaseConnection();

    // CREATE operation: Add a new entry to the database (ID will be generated by the sequence)
    public String addEntry(WorkHourEntry entry) {
        // Use the sequence to generate ID for insertion
        String sql = "INSERT INTO WorkHours (ID, Name, Role, Hours) VALUES (workhours_seq.NEXTVAL, ?, ?, ?)";

        try (PreparedStatement ps = db.connection.prepareStatement(sql)) {
            // Set values for the prepared statement (Name, Role, Hours)
            ps.setString(1, entry.getName());
            ps.setString(2, entry.getRole());
            ps.setDouble(3, entry.getHours());  // Use setDouble for fractional hours if needed

            // Execute the insert operation
            int rows = ps.executeUpdate();

            // Check if the entry was successfully added
            if (rows > 0) {
                return "Entry added successfully.";
            } else {
                return "Failed to add entry.";
            }

        } catch (SQLException e) {
            // Return any errors encountered during the SQL execution
            return "Error: " + e.getMessage();
        }
    }

    // READ ALL operation: Retrieve all entries from the database
    public List<WorkHourEntry> getAllEntries() {
        List<WorkHourEntry> entries = new ArrayList<>();
        String sql = "SELECT * FROM WorkHours ORDER BY ID";

        try (PreparedStatement ps = db.connection.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            // Loop through the result set and create WorkHourEntry objects
            while (rs.next()) {
                WorkHourEntry entry = new WorkHourEntry(
                        rs.getInt("ID"),
                        rs.getString("Name"),
                        rs.getString("Role"),
                        rs.getDouble("Hours")  // Retrieve hours as double (to handle fractional hours)
                );
                entries.add(entry);  // Add each entry to the list
            }

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }

        // Return the list of entries
        return entries;
    }

    // READ BY ID operation: Retrieve a single entry by its ID
    public WorkHourEntry getEntryById(int id) {
        String sql = "SELECT * FROM WorkHours WHERE ID = ?";
        try (PreparedStatement ps = db.connection.prepareStatement(sql)) {
            ps.setInt(1, id);

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    return new WorkHourEntry(
                            rs.getInt("ID"),
                            rs.getString("Name"),
                            rs.getString("Role"),
                            rs.getDouble("Hours")  // Retrieve hours as double
                    );
                }
            }

        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
        return null;  // If not found
    }

    // UPDATE operation: Update an existing entry in the database
    public String updateEntry(WorkHourEntry entry) {
        String sql = "UPDATE WorkHours SET Name = ?, Role = ?, Hours = ? WHERE ID = ?";
        try (PreparedStatement ps = db.connection.prepareStatement(sql)) {
            ps.setString(1, entry.getName());
            ps.setString(2, entry.getRole());
            ps.setDouble(3, entry.getHours());  // Use setDouble for hours (fractional support)
            ps.setInt(4, entry.getId());

            int rows = ps.executeUpdate();

            return rows > 0 ? "Entry updated successfully." : "No entry found.";
        } catch (SQLException e) {
            return "Error: " + e.getMessage();
        }
    }

    // DELETE operation: Delete an entry by its ID
    public String deleteEntry(int id) {
        String sql = "DELETE FROM WorkHours WHERE ID = ?";
        try (PreparedStatement ps = db.connection.prepareStatement(sql)) {
            ps.setInt(1, id);

            int rows = ps.executeUpdate();

            return rows > 0 ? "Entry deleted successfully." : "No entry found.";
        } catch (SQLException e) {
            return "Error: " + e.getMessage();
        }
    }
}